## PART A NUMPY FUNDAMENTALS

# Problem 1: Array creation and dtypes(10 points)


Create the following arrays:
1. A 1D array a containing the integers 0 through 19.
2. A 2D array b with shape (4, 5) containing the same values as a in row-major order.
3. A float array c that is the result of dividing b by 3.
Report the shape and dtype of each array and briefly explain why c has its dtype.

In [1]:
import numpy as np

# 1) 1D array a: integers 0 through 19
a = np.arange(20)

# 2) 2D array b: shape (4, 5) using row-major order
b = a.reshape(4, 5)

# 3) float array c: divide b by 3
c = b / 3

print("a:\n", a)
print("a shape:", a.shape, "| a dtype:", a.dtype, "\n")

print("b:\n", b)
print("b shape:", b.shape, "| b dtype:", b.dtype, "\n")

print("c:\n", c)
print("c shape:", c.shape, "| c dtype:", c.dtype)

a:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
a shape: (20,) | a dtype: int64 

b:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
b shape: (4, 5) | b dtype: int64 

c:
 [[0.         0.33333333 0.66666667 1.         1.33333333]
 [1.66666667 2.         2.33333333 2.66666667 3.        ]
 [3.33333333 3.66666667 4.         4.33333333 4.66666667]
 [5.         5.33333333 5.66666667 6.         6.33333333]]
c shape: (4, 5) | c dtype: float64


# Brief Explnation


c is a float array because integer values 3 uses true division, which can produce non-integer results. Numpy protects the dtype from integer to floating point to represent those decimals.

## Problem 2: Indexing, slicing, and boolean masks (10 points)

Using b from Problem 1:
1. Extract the last column of b.
2. Extract the sub-matrix consisting of rows 1–2 and columns 2–4.
3. Create a boolean mask for entries of b that are divisible by 3, and use it to return those values
as a 1D array.
4. Replace all values in b that are greater than 12 with -1 (without using Python loops).

In [2]:
# 1. Extract the last column of b
last_column = b[:, -1]
print("1. Last column of b:")
print(last_column)
print()

# 2. Extract sub-matrix (rows 1-2, columns 2-4)
sub_matrix = b[1:3, 2:5]
print("2. Sub-matrix (rows 1-2, columns 2-4):")
print(sub_matrix)
print()

# 3. Boolean mask for entries divisible by 3
mask = (b % 3 == 0)
values_divisible_by_3 = b[mask]
print("3. Boolean mask (divisible by 3):")
print(mask)
print("\nValues divisible by 3:")
print(values_divisible_by_3)
print()

# 4. Replace values greater than 12 with -1
b_modified = b.copy()
b_modified[b_modified > 12] = -1
print("4. Array b with values > 12 replaced by -1:")
print(b_modified)

1. Last column of b:
[ 4  9 14 19]

2. Sub-matrix (rows 1-2, columns 2-4):
[[ 7  8  9]
 [12 13 14]]

3. Boolean mask (divisible by 3):
[[ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]]

Values divisible by 3:
[ 0  3  6  9 12 15 18]

4. Array b with values > 12 replaced by -1:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 -1 -1]
 [-1 -1 -1 -1 -1]]


## Problem 3: Vectorized computation (10 points)

Let x be a length-100 NumPy array of random values drawn from a standard normal distribution
(use a fixed seed).
1. Compute the z-scores of x: z = (x − ¯x)/s using vectorized operations.
2. Verify (numerically) that the mean of z is approximately 0 and the standard deviation is ap-
proximately 1.
3. Compute the proportion of entries of z that fall in the interval [−1, 1].
State the seed you used.

In [3]:
# Set seed for reproducibility
np.random.seed(42)
print(f"Seed used: 42")

# Generate length-100 array from standard normal distribution
x = np.random.randn(100)

# 1. Compute z-scores using vectorized operations
x_mean = x.mean()
x_std = x.std()
z = (x - x_mean) / x_std

print(f"\n1. Z-scores computed using: z = (x - mean) / std")
print(f"   First 10 z-scores: {z[:10]}")

# 2. 
z_mean = z.mean()
z_std = z.std()

print(f"\n2. Verification:")
print(f"   Mean of z: {z_mean:.10f} (approximately 0)")
print(f"   Standard deviation of z: {z_std:.10f} (approximately 1)")

# 3. Compute proportion in interval [-1, 1]
in_interval = np.logical_and(z >= -1, z <= 1)
proportion = in_interval.sum() / len(z)

print(f"\n3. Proportion of z in [-1, 1]: {proportion:.4f} ({proportion*100:.2f}%)")
print(f"   Number of values in [-1, 1]: {in_interval.sum()} out of {len(z)}")


Seed used: 42

1. Z-scores computed using: z = (x - mean) / std
   First 10 z-scores: [ 0.66461921 -0.03808894  0.83169721  1.80040643 -0.14420598 -0.14418781
  1.86258212  0.96421608 -0.4046274   0.71535523]

2. Verification:
   Mean of z: -0.0000000000 (approximately 0)
   Standard deviation of z: 1.0000000000 (approximately 1)

3. Proportion of z in [-1, 1]: 0.6500 (65.00%)
   Number of values in [-1, 1]: 65 out of 100


## Problem 4: Aggregation and axis reasoning (10 points)

Create an array M with shape (6, 4) containing random integers from 0 to 9 (use a fixed seed).
1. Compute the sum of each row and store it as a 1D array row sums.
2. Compute the mean of each column and store it as a 1D array col means.
3. Find the index (row, column) of the maximum value in M.
4. Standardize each column of M to have mean 0 and standard deviation 1 (column-wise standard-
ization). Report the mean and std of each standardized column to confirm.

In [4]:
# Set seed for reproducibility
np.random.seed(123)
print(f"Seed used: 123")

# Create 6x4 array with random integers from 0 to 9
M = np.random.randint(0, 10, size=(6, 4))
print(f"\nArray M (shape {M.shape}):")
print(M)

# 1. Compute sum of each row
row_sums = M.sum(axis=1)
print(f"\n1. Row sums (sum along axis=1):")
print(row_sums)
print(f"   Shape: {row_sums.shape}")

# 2. Compute mean of each column
col_means = M.mean(axis=0)
print(f"\n2. Column means (mean along axis=0):")
print(col_means)
print(f"   Shape: {col_means.shape}")

# 3. Find index (row, column) of maximum value
max_value = M.max()
max_index = np.unravel_index(M.argmax(), M.shape)
print(f"\n3. Maximum value in M: {max_value}")
print(f"   Index (row, column): {max_index}")
print(f"   Verification: M[{max_index[0]}, {max_index[1]}] = {M[max_index[0], max_index[1]]}")

# 4. Standardize each column (mean=0, std=1)
M_standardized = (M - M.mean(axis=0)) / M.std(axis=0)
print(f"\n4. Column-wise standardization:")
print(f"   Standardized array M:")
print(M_standardized)

# Verify standardization
standardized_means = M_standardized.mean(axis=0)
standardized_stds = M_standardized.std(axis=0)
print(f"\n   Verification - Mean of each standardized column:")
print(f"   {standardized_means}")
print(f"\n   Verification - Std of each standardized column:")
print(f"   {standardized_stds}")


Seed used: 123

Array M (shape (6, 4)):
[[2 2 6 1]
 [3 9 6 1]
 [0 1 9 0]
 [0 9 3 4]
 [0 0 4 1]
 [7 3 2 4]]

1. Row sums (sum along axis=1):
[11 19 10 16  5 16]
   Shape: (6,)

2. Column means (mean along axis=0):
[2.         4.         5.         1.83333333]
   Shape: (4,)

3. Maximum value in M: 9
   Index (row, column): (np.int64(1), np.int64(1))
   Verification: M[1, 1] = 9

4. Column-wise standardization:
   Standardized array M:
[[ 0.         -0.54772256  0.4330127  -0.52999894]
 [ 0.39735971  1.36930639  0.4330127  -0.52999894]
 [-0.79471941 -0.82158384  1.73205081 -1.16599767]
 [-0.79471941  1.36930639 -0.8660254   1.37799724]
 [-0.79471941 -1.09544512 -0.4330127  -0.52999894]
 [ 1.98679854 -0.27386128 -1.29903811  1.37799724]]

   Verification - Mean of each standardized column:
   [-3.70074342e-17  5.55111512e-17 -3.70074342e-17  3.70074342e-17]

   Verification - Std of each standardized column:
   [1. 1. 1. 1.]


## Problem 5: Linear algebra basics (10 points)

1. Compute Av using NumPy.
2. Compute the determinant of A.
3. Compute the eigenvalues of A (numerically).
4. Solve Ax = v for x.
Briefly explain (1–2 sentences) when you would use np.linalg.solve instead of explicitly com-
puting A^-1



In [5]:
# Define matrix A and vector v
A = np.array([[2, 1, 0],
              [1, 3, 1],
              [0, 1, 2]])

v = np.array([[1],
              [2],
              [3]])

print("Matrix A:")
print(A)
print(f"\nVector v:")
print(v)

# 1. Compute Av using NumPy
Av = A @ v  # or np.dot(A, v) or A.dot(v)
print(f"\n1. Av (matrix-vector multiplication):")
print(Av)

# 2. Compute the determinant of A
det_A = np.linalg.det(A)
print(f"\n2. Determinant of A: {det_A}")

# 3. Compute eigenvalues of A (numerically)
eigenvalues = np.linalg.eigvals(A)
print(f"\n3. Eigenvalues of A:")
print(eigenvalues)

# 4. Solve Ax = v for x
x = np.linalg.solve(A, v)
print(f"\n4. Solution to Av = v  for x:")
print(x)


Matrix A:
[[2 1 0]
 [1 3 1]
 [0 1 2]]

Vector v:
[[1]
 [2]
 [3]]

1. Av (matrix-vector multiplication):
[[ 4]
 [10]
 [ 8]]

2. Determinant of A: 8.000000000000002

3. Eigenvalues of A:
[4. 2. 1.]

4. Solution to Av = v  for x:
[[5.0000000e-01]
 [8.8817842e-17]
 [1.5000000e+00]]


## Brief Explanation
We should use np.linalog.solve instead of explicitly computing A⁻¹ because it is more numerically stable and have efficient computation. The solve function uses algorithms like LU decomposition that are faster and less prone to rounding errors than explicitly inverting a matrix.

## PART B: PANDAS
 # Problem 6: Basic DataFrame inspection (8 points)

Using df:
1. Show df.head() and df.info() (or equivalent summary).
2. Convert the date column to a datetime type and confirm the dtype changed.
3. Add a new column revenue equal to units * unit price

In [6]:
import pandas as pd

records = [
    {"order_id": 101, "date": "2026-01-03", "customer": "Ava", "city": "Boston", "category": "Books", "units": 2, "unit_price": 12.50},
    {"order_id": 102, "date": "2026-01-03", "customer": "Noah", "city": "Boston", "category": "Games", "units": 1, "unit_price": 59.99},
    {"order_id": 103, "date": "2026-01-04", "customer": "Ava", "city": "Seattle", "category": "Books", "units": 3, "unit_price": 12.50},
    {"order_id": 104, "date": "2026-01-05", "customer": "Mia", "city": "Seattle", "category": "Garden", "units": 4, "unit_price": 7.25},
    {"order_id": 105, "date": "2026-01-05", "customer": "Liam", "city": "Austin", "category": "Books", "units": 1, "unit_price": 20.00},
    {"order_id": 106, "date": "2026-01-06", "customer": "Noah", "city": "Austin", "category": "Garden", "units": 2, "unit_price": 7.25},
    {"order_id": 107, "date": "2026-01-07", "customer": "Mia", "city": "Boston", "category": "Games", "units": 2, "unit_price": 59.99},
    {"order_id": 108, "date": "2026-01-08", "customer": "Ava", "city": "Austin", "category": "Books", "units": 2, "unit_price": 12.50},
]

df = pd.DataFrame(records)

# 1. Show df.head() and df.info()
print("\ndf.head():")
print(df.head())

print("\ndf.info():")
df.info()

# 2. Convert date column to datetime type
print("\n2. Converting 'date' column to datetime:")
print(f"   Before conversion - dtype: {df['date'].dtype}")

df['date'] = pd.to_datetime(df['date'])

print(f"   After conversion - dtype: {df['date'].dtype}")
print(f"   Confirmation: dtype changed from 'object' to 'datetime64[ns]'")

# 3. Add new column revenue = units * unit_price
df['revenue'] = df['units'] * df['unit_price']

print("\n3. Added 'revenue' column (units * unit_price):")
print(df)

print(f"\nDataFrame shape: {df.shape}")
print(f"Column names: {df.columns.tolist()}")


df.head():
   order_id        date customer     city category  units  unit_price
0       101  2026-01-03      Ava   Boston    Books      2       12.50
1       102  2026-01-03     Noah   Boston    Games      1       59.99
2       103  2026-01-04      Ava  Seattle    Books      3       12.50
3       104  2026-01-05      Mia  Seattle   Garden      4        7.25
4       105  2026-01-05     Liam   Austin    Books      1       20.00

df.info():
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   order_id    8 non-null      int64  
 1   date        8 non-null      str    
 2   customer    8 non-null      str    
 3   city        8 non-null      str    
 4   category    8 non-null      str    
 5   units       8 non-null      int64  
 6   unit_price  8 non-null      float64
dtypes: float64(1), int64(2), str(4)
memory usage: 580.0 bytes

2. Converting 'date' column to dat

## Problem 7: Filtering and sorting (8 points)
1. Filter orders that occurred in Boston or have category Garden.
2. From that filtered result, sort by date ascending, then by revenue descending.
3. Return only the columns order id, date, city, category, revenue

In [7]:
# 1. Filter orders in Boston OR category Garden
filtered_df = df[(df['city'] == 'Boston') | (df['category'] == 'Garden')]

print("\n1. Filtered orders (Boston OR Garden category):")
print(filtered_df)
print(f"   Number of records: {len(filtered_df)}")

# from that filtered result, sort by date ascending, then by revenue descending.
sorted_df = filtered_df.sort_values(by=['date', 'revenue'], ascending=[True, False])

print("\n2. Sorted by date (ascending), then revenue (descending):")
print(sorted_df)

# Return only the columns order id, date, city, category, revenue
result = sorted_df[['order_id', 'date', 'city', 'category', 'revenue']]

print("\n3. Final result (selected columns only):")
print(result)
print(f"\n   Final shape: {result.shape}")



1. Filtered orders (Boston OR Garden category):
   order_id       date customer     city category  units  unit_price  revenue
0       101 2026-01-03      Ava   Boston    Books      2       12.50    25.00
1       102 2026-01-03     Noah   Boston    Games      1       59.99    59.99
3       104 2026-01-05      Mia  Seattle   Garden      4        7.25    29.00
5       106 2026-01-06     Noah   Austin   Garden      2        7.25    14.50
6       107 2026-01-07      Mia   Boston    Games      2       59.99   119.98
   Number of records: 5

2. Sorted by date (ascending), then revenue (descending):
   order_id       date customer     city category  units  unit_price  revenue
1       102 2026-01-03     Noah   Boston    Games      1       59.99    59.99
0       101 2026-01-03      Ava   Boston    Books      2       12.50    25.00
3       104 2026-01-05      Mia  Seattle   Garden      4        7.25    29.00
5       106 2026-01-06     Noah   Austin   Garden      2        7.25    14.50
6       10

## Problem 8: GroupBy aggregations (10 points)
Compute a summary table by city with:
• total revenue,
• total units,
• number of distinct customers,
• average unit price (simple mean of unit price).
Sort cities by total revenue (descending).

In [8]:
# Group by city and compute aggregations
city_summary = df.groupby('city')

# Calculate each metric separately
total_revenue = city_summary['revenue'].sum()
total_units = city_summary['units'].sum()
distinct_customers = city_summary['customer'].nunique()
avg_unit_price = city_summary['unit_price'].mean()

# Combine into a DataFrame
summary = pd.DataFrame({
    'total_revenue': total_revenue,
    'total_units': total_units,
    'distinct_customers': distinct_customers,
    'avg_unit_price': avg_unit_price
})

# Sort by total revenue descending
summary = summary.sort_values('total_revenue', ascending=False)

print("\nSummary table by city (sorted by total revenue descending):")
print(summary)



Summary table by city (sorted by total revenue descending):
         total_revenue  total_units  distinct_customers  avg_unit_price
city                                                                   
Boston          204.97            5                   3          44.160
Seattle          66.50            7                   2           9.875
Austin           59.50            5                   3          13.250


## Problem 9: Pivot table (8 points)
Create a pivot table with:
• index = date
• columns = category
• values = total revenue
Fill missing values with 0.

In [9]:
# Create pivot table
pivot = df.pivot_table(
    index='date',
    columns='category',
    values='revenue',
    aggfunc='sum',
    fill_value=0
)

print("\nPivot table (date × category, values = total revenue):")
print(pivot)

print(f"\nPivot table shape: {pivot.shape}")
print(f"Index (dates): {len(pivot)} unique dates")
print(f"Columns (categories): {pivot.columns.tolist()}")


Pivot table (date × category, values = total revenue):
category    Books   Games  Garden
date                             
2026-01-03   25.0   59.99     0.0
2026-01-04   37.5    0.00     0.0
2026-01-05   20.0    0.00    29.0
2026-01-06    0.0    0.00    14.5
2026-01-07    0.0  119.98     0.0
2026-01-08   25.0    0.00     0.0

Pivot table shape: (6, 3)
Index (dates): 6 unique dates
Columns (categories): ['Books', 'Games', 'Garden']


## Problem 10: Merging (8 points)
Create a second DataFrame:

customer_tier = pd.DataFrame({
"customer": ["Ava", "Noah", "Mia", "Liam"],
"tier": ["Gold", "Silver", "Gold", "Bronze"]
})
1. Merge df with customer tier to add the tier to each order.
2. Compute total revenue by tier.

In [10]:
# Create second DataFrame
customer_tier = pd.DataFrame({
    "customer": ["Ava", "Noah", "Mia", "Liam"],
    "tier": ["Gold", "Silver", "Gold", "Bronze"]
})

print("\nCustomer tier DataFrame:")
print(customer_tier)

# 1. Merge df with customer_tier
df_merged = df.merge(customer_tier, on='customer', how='left')

print("\n1. Merged DataFrame (df + tier column):")
print(df_merged)

# 2. Compute total revenue by tier
revenue_by_tier = df_merged.groupby('tier')['revenue'].sum().sort_values(ascending=False)

print("\n2. Total revenue by tier:")
print(revenue_by_tier)

# Alternative: as DataFrame
revenue_by_tier_df = df_merged.groupby('tier')['revenue'].sum().reset_index()
revenue_by_tier_df.columns = ['tier', 'total_revenue']
revenue_by_tier_df = revenue_by_tier_df.sort_values('total_revenue', ascending=False)

print("\n   As DataFrame:")
print(revenue_by_tier_df)


Customer tier DataFrame:
  customer    tier
0      Ava    Gold
1     Noah  Silver
2      Mia    Gold
3     Liam  Bronze

1. Merged DataFrame (df + tier column):
   order_id       date customer     city category  units  unit_price  revenue  \
0       101 2026-01-03      Ava   Boston    Books      2       12.50    25.00   
1       102 2026-01-03     Noah   Boston    Games      1       59.99    59.99   
2       103 2026-01-04      Ava  Seattle    Books      3       12.50    37.50   
3       104 2026-01-05      Mia  Seattle   Garden      4        7.25    29.00   
4       105 2026-01-05     Liam   Austin    Books      1       20.00    20.00   
5       106 2026-01-06     Noah   Austin   Garden      2        7.25    14.50   
6       107 2026-01-07      Mia   Boston    Games      2       59.99   119.98   
7       108 2026-01-08      Ava   Austin    Books      2       12.50    25.00   

     tier  
0    Gold  
1  Silver  
2    Gold  
3    Gold  
4  Bronze  
5  Silver  
6    Gold  
7    Gold  


## Problem 11: Missing data (8 points)
Make a copy of df called df2 and then:
1. Set unit price to missing (NaN) for order id == 106.
2. Show how many missing values each column has.
3. Replace missing unit price with the median unit price within the same category. (Hint:
groupby + transform.)
4. Recompute revenue for df2 and verify order id 106 now has a non-missing revenue.

In [11]:
# Make a copy of df
df2 = df.copy()

# 1. Set unit_price to NaN for order_id == 106
df2.loc[df2['order_id'] == 106, 'unit_price'] = np.nan

print("\n1. Set unit_price to NaN for order_id == 106:")
print(df2[df2['order_id'] == 106])

# 2. Show how many missing values each column has
missing_counts = df2.isnull().sum()

print("\n2. Missing values per column:")
print(missing_counts)

# 3. Replace missing unit_price with median within same category
df2['unit_price'] = df2.groupby('category')['unit_price'].transform(lambda x: x.fillna(x.median()))

print("\n3. After filling missing unit_price with category median:")
print(df2[df2['order_id'] == 106])

# 4. Recompute revenue for df2
df2['revenue'] = df2['units'] * df2['unit_price']

print("\n4. Recomputed revenue for df2:")
print(df2[df2['order_id'] == 106])

# Verify order_id 106 now has non-missing revenue
print(f"\n   Verification:")
print(f"   Order 106 revenue is NaN: {df2[df2['order_id'] == 106]['revenue'].isna().values[0]}")
print(f"   Order 106 revenue value: {df2[df2['order_id'] == 106]['revenue'].values[0]:.2f}")


1. Set unit_price to NaN for order_id == 106:
   order_id       date customer    city category  units  unit_price  revenue
5       106 2026-01-06     Noah  Austin   Garden      2         NaN     14.5

2. Missing values per column:
order_id      0
date          0
customer      0
city          0
category      0
units         0
unit_price    1
revenue       0
dtype: int64

3. After filling missing unit_price with category median:
   order_id       date customer    city category  units  unit_price  revenue
5       106 2026-01-06     Noah  Austin   Garden      2        7.25     14.5

4. Recomputed revenue for df2:
   order_id       date customer    city category  units  unit_price  revenue
5       106 2026-01-06     Noah  Austin   Garden      2        7.25     14.5

   Verification:
   Order 106 revenue is NaN: False
   Order 106 revenue value: 14.50
