## PART A NUMPY FUNDAMENTALS

# Problem 1: Array creation and dtypes(10 points)


Create the following arrays:
1. A 1D array a containing the integers 0 through 19.
2. A 2D array b with shape (4, 5) containing the same values as a in row-major order.
3. A float array c that is the result of dividing b by 3.
Report the shape and dtype of each array and briefly explain why c has its dtype.

In [2]:
import numpy as np

# 1) 1D array a: integers 0 through 19
a = np.arange(20)

# 2) 2D array b: shape (4, 5) using row-major order
b = a.reshape(4, 5)

# 3) float array c: divide b by 3
c = b / 3

print("a:\n", a)
print("a shape:", a.shape, "| a dtype:", a.dtype, "\n")

print("b:\n", b)
print("b shape:", b.shape, "| b dtype:", b.dtype, "\n")

print("c:\n", c)
print("c shape:", c.shape, "| c dtype:", c.dtype)

a:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
a shape: (20,) | a dtype: int64 

b:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
b shape: (4, 5) | b dtype: int64 

c:
 [[0.         0.33333333 0.66666667 1.         1.33333333]
 [1.66666667 2.         2.33333333 2.66666667 3.        ]
 [3.33333333 3.66666667 4.         4.33333333 4.66666667]
 [5.         5.33333333 5.66666667 6.         6.33333333]]
c shape: (4, 5) | c dtype: float64


# Brief Explnation


c is a float array because integer values 3 uses true division, which can produce non-integer results. Numpy protects the dtype from integer to floating point to represent those decimals.

## Problem 2: Indexing, slicing, and boolean masks (10 points)

Using b from Problem 1:
1. Extract the last column of b.
2. Extract the sub-matrix consisting of rows 1–2 and columns 2–4.
3. Create a boolean mask for entries of b that are divisible by 3, and use it to return those values
as a 1D array.
4. Replace all values in b that are greater than 12 with -1 (without using Python loops).

In [6]:
# 1. Extract the last column of b
last_column = b[:, -1]
print("1. Last column of b:")
print(last_column)
print()

# 2. Extract sub-matrix (rows 1-2, columns 2-4)
sub_matrix = b[1:3, 2:5]
print("2. Sub-matrix (rows 1-2, columns 2-4):")
print(sub_matrix)
print()

# 3. Boolean mask for entries divisible by 3
mask = (b % 3 == 0)
values_divisible_by_3 = b[mask]
print("3. Boolean mask (divisible by 3):")
print(mask)
print("\nValues divisible by 3:")
print(values_divisible_by_3)
print()

# 4. Replace values greater than 12 with -1
b_modified = b.copy()
b_modified[b_modified > 12] = -1
print("4. Array b with values > 12 replaced by -1:")
print(b_modified)

1. Last column of b:
[ 4  9 14 19]

2. Sub-matrix (rows 1-2, columns 2-4):
[[ 7  8  9]
 [12 13 14]]

3. Boolean mask (divisible by 3):
[[ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]]

Values divisible by 3:
[ 0  3  6  9 12 15 18]

4. Array b with values > 12 replaced by -1:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 -1 -1]
 [-1 -1 -1 -1 -1]]


## Problem 3: Vectorized computation (10 points)

Let x be a length-100 NumPy array of random values drawn from a standard normal distribution
(use a fixed seed).
1. Compute the z-scores of x: z = (x − ¯x)/s using vectorized operations.
2. Verify (numerically) that the mean of z is approximately 0 and the standard deviation is ap-
proximately 1.
3. Compute the proportion of entries of z that fall in the interval [−1, 1].
State the seed you used.

In [11]:
# Set seed for reproducibility
np.random.seed(42)
print(f"Seed used: 42")

# Generate length-100 array from standard normal distribution
x = np.random.randn(100)

# 1. Compute z-scores using vectorized operations
x_mean = x.mean()
x_std = x.std()
z = (x - x_mean) / x_std

print(f"\n1. Z-scores computed using: z = (x - mean) / std")
print(f"   First 10 z-scores: {z[:10]}")

# 2. 
z_mean = z.mean()
z_std = z.std()

print(f"\n2. Verification:")
print(f"   Mean of z: {z_mean:.10f} (approximately 0)")
print(f"   Standard deviation of z: {z_std:.10f} (approximately 1)")

# 3. Compute proportion in interval [-1, 1]
in_interval = np.logical_and(z >= -1, z <= 1)
proportion = in_interval.sum() / len(z)

print(f"\n3. Proportion of z in [-1, 1]: {proportion:.4f} ({proportion*100:.2f}%)")
print(f"   Number of values in [-1, 1]: {in_interval.sum()} out of {len(z)}")


Seed used: 42

1. Z-scores computed using: z = (x - mean) / std
   First 10 z-scores: [ 0.66461921 -0.03808894  0.83169721  1.80040643 -0.14420598 -0.14418781
  1.86258212  0.96421608 -0.4046274   0.71535523]

2. Verification:
   Mean of z: -0.0000000000 (approximately 0)
   Standard deviation of z: 1.0000000000 (approximately 1)

3. Proportion of z in [-1, 1]: 0.6500 (65.00%)
   Number of values in [-1, 1]: 65 out of 100
