## PART A NUMPY FUNDAMENTALS

# Problem 1: Array creation and dtypes(10 points)


Create the following arrays:
1. A 1D array a containing the integers 0 through 19.
2. A 2D array b with shape (4, 5) containing the same values as a in row-major order.
3. A float array c that is the result of dividing b by 3.
Report the shape and dtype of each array and briefly explain why c has its dtype.

In [2]:
import numpy as np

# 1) 1D array a: integers 0 through 19
a = np.arange(20)

# 2) 2D array b: shape (4, 5) using row-major order
b = a.reshape(4, 5)

# 3) float array c: divide b by 3
c = b / 3

print("a:\n", a)
print("a shape:", a.shape, "| a dtype:", a.dtype, "\n")

print("b:\n", b)
print("b shape:", b.shape, "| b dtype:", b.dtype, "\n")

print("c:\n", c)
print("c shape:", c.shape, "| c dtype:", c.dtype)

a:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
a shape: (20,) | a dtype: int64 

b:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
b shape: (4, 5) | b dtype: int64 

c:
 [[0.         0.33333333 0.66666667 1.         1.33333333]
 [1.66666667 2.         2.33333333 2.66666667 3.        ]
 [3.33333333 3.66666667 4.         4.33333333 4.66666667]
 [5.         5.33333333 5.66666667 6.         6.33333333]]
c shape: (4, 5) | c dtype: float64


# Brief Explnation


c is a float array because integer values 3 uses true division, which can produce non-integer results. Numpy protects the dtype from integer to floating point to represent those decimals.